auth0:
  audience: https://dev-0yczl7li.us.auth0.com/api/v2/
spring:
  security.oauth2.resourceserver.jwt.issuer-uri: https://dev-0yczl7li.us.auth0.com/
  datasource:
    url: ${POSTGRES_DATABASE_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
#    url: jdbc:postgresql://ec2-54-225-14-17.compute-1.amazonaws.com:5432/d3q7r6aktr0adh?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=true&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    hikari:
      connectionTimeout: 5000
      maximumPoolSize: 5

  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="gg51lf9u" password="sn6w0kN4GUAySZScy1USUhxoQzeV2rgW";
    bootstrap-servers: tricycle-01.srvs.cloudkafka.com:9094,tricycle-02.srvs.cloudkafka.com:9094,tricycle-03.srvs.cloudkafka.com:9094
    consumer:
      group-id: gisa-users-api



  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

user:
  topic: gg51lf9u-user-event-topic-v1

logging.level.root: INFO


